modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory
license="MIT"

[[mods]] #mandatory
modId="stevenmod" #mandatory
version="1.1" #mandatory
displayName="Steven Mod" #mandatory
logoFile="stevenmod.png" #optional
credits="axd" #optional
authors="axd" #optional

description='''
A mod based on Steven He.
'''